name: Release

permissions:
  contents: write

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cargo cache
      uses: Swatinem/rust-cache@v2
    - name: Build and upload
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: voxircle
        zip: windows
        token: ${{ secrets.GITHUB_TOKEN }}
